export const IS_LOGIN = "IS_LOGIN";
export const USER_LOADING = "USER_LOADING";
export const USER_LOADED = "USER_LOADED";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const LOGOUT_FAIL = "LOGOUT_FAIL";
export const AUTH_ERROR = "AUTH_ERROR";
export const SIGN_UP_SUCCESS = "SIGN_UP_SUCCESS";
export const SIGN_UP_FAILED = "SIGN_UP_FAILED";
export const POPULAR_BOOKS_FETCH_SUCCESS = "POPULAR_BOOKS_FETCH_SUCCESS";
export const BOOKS_FETCH_SUCCESS = "BOOKS_FETCH_SUCCESS";
export const BOOKS_FETCH_FAILED = "BOOKS_FETCH_FAILED";
export const BOOK_FETCH_BY_ID_SUCCESS = "BOOK_FETCH_BY_ID_SUCCESS"
export const POPULAR_BOOKS_FETCH_FAILED = "POPULAR_BOOKS_FETCH_FAILED";
export const GET_IMP_DATA_SUCCESS = "GET_IMP_DATA_SUCCESS";
export const GET_IMP_DATA_FAILED = "GET_IMP_DATA_FAILED";
export const ADD_BOOK_SUCCESS = "ADD_BOOK_SUCCESS";
export const ADD_BOOK_FAILED = "ADD_BOOK_FAILED";
export const SEARCH_SUCCESS = "SEARCH_SUCCESS";
export const SEARCH_FAILED = "SEARCH_FAILED";
export const DELETE_SUCCESS = "DELETE_SUCCESS";
export const DELETE_FAILED = "DELETE_FAILED";
export const EDIT_BOOK_SUCCESS = "EDIT_BOOK_SUCCESS";
export const EDIT_BOOK_FAILED = "EDIT_BOOK_FAILED";

export const REFRESH_TOKEN_SUCCESS = "REFRESH_TOKEN_SUCCESS";
export const REFRESH_TOKEN_FAILED = "REFRESH_TOKEN_FAILED";



export const LOAD_NOTIFICATION = "LOAD_NOTIFICATION";
export const CLEAR_NOTIFICATION = "CLEAR_NOTIFICATION";

export const CLEAR_NOTIFICATION_STARTER = "CLEAR_NOTIFICATION_STARTER";
export const START_LOADING = "START_LOADING";
export const STOP_LOADING = "STOP_LOADING";